name: Vercel Preview Deployment with JSON Server
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}

      - name: Build Project Artifacts
        run: vercel build --token=${VERCEL_TOKEN}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${VERCEL_TOKEN}

      - name: Install JSON Server
        run: npm install -g json-server

      - name: Start JSON Server
        run: json-server --watch data.json --port 3000
